language: go

go:
    - 1.4

before_install:
  - go get github.com/tcnksm/ghr

after_success:
  - go build 
  - ghr  --username sentinel-tools --token $GITHUB_TOKEN --replace $(cat .version) pod-connector
