language: go

go:
    - 1.4

before_install:
  - go get github.com/tcnksm/ghr

after_success:
  - go build 
  - ghr -r sentinel-tools/pod-connector --username therealbill --token $GITHUB_TOKEN --replace $(cat .version) pod-connector
